run_logged $INSTALL_SCRIPT_LOCATION/config/config.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/theme.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/git.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/timezones.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/ssh-flakiness.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/detect-keyboard-layout.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/fix-powerprofilesctl-shebang.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/mimetypes.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/localdb.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/network.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/set-wireless-regdom.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/fix-fkeys.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/bluetooth.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/printer.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/usb-autosuspend.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/ignore-power-button.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/nvidia.sh
run_logged $INSTALL_SCRIPT_LOCATION/config/hardware/fix-f13-amd-audio-input.sh
